### ISSUE TITLE
"Most Popular Post"  Missing answer images.

### ISSUE THREAD

**Issue by nofi79** [chris-kent/Easy-Forums#10]
Hi,

When we have a most popular post with images in the post, the pics does not appear in the mos popular post. 

Most Popular Post.
![image](https://cloud.githubusercontent.com/assets/1111059/23761234/e17a9f14-04d0-11e7-8924-e556882ffeed.png)

Normal Post:
![image](https://cloud.githubusercontent.com/assets/1111059/23761274/01443210-04d1-11e7-9c47-7ec23f5a766b.png)

Could it be a bug or it is not to have images on the most popular post ?

**Comment by chris-kent** [comment]
Hi there.

Yes this looks like a bug. I will schedule the fix for the next release.

Cheers

**Comment by chris-kent** [comment]
Hi there,

I have fixed this in version 2.10.

If you like my plugin, please leave a review, I don't many :(

Cheers
Chris

**Comment by nofi79** [comment]
Hi Chris,

I am only the moderator of the forum all technical information are carried out by our It team. I have open new tickets issues related with easy-forum asking them to upgrade the software and set the customizing page as you said. 

Is there a way to check easy-forum version without admin priveleges ?

**Comment by chris-kent** [comment]
Hi,

Unfortunately only Confluence administrators manage and know the versions
of plugins. However, I could easily put a version number on the Home page
(below the table of Forums in the Space) for Moderators and Admins to see
quickly.

Let me know if this would interest you?

Cheers
Chris

**Comment by chris-kent** [comment]
Hi,

I just added another version 2.12, which shows you the plugin version on the Home page.

Cheers
Chris

**Comment by nofi79** [comment]
Hi Cris, 

We just updated to version 2.11 and all images are working properly in the most popular post. 

![image](https://cloud.githubusercontent.com/assets/1111059/24045278/45dd9f38-0afd-11e7-9819-15936d61fc76.png)

I will ask to out IT team to upgrade to version 2.12. Place easy-forum version at bottom page was a great idea and it is now as confluence show the version..

Thanks for all your help.

**Comment by nofi79** [comment]
Hi Cris, 

We just updated to version 2.13 and there is an error related with the easy-forum version. You can see  highlighted in the image below.

![image](https://cloud.githubusercontent.com/assets/1111059/24045978/a29c0a78-0aff-11e7-8a0e-8546056386e0.png)

Could it be a problem with the easy-forum version ?

**Comment by chris-kent** [comment]
Hi,

I am not sure, on this one. Can you try one thing for me? Go to the Easy
Forums admin page, change the option on both "Show Sidebar" and "Show
Labels", press Save.
Then refresh the screen and see if that is working?

Otherwise if it still shows an error, please send me a Confluence log after
enabling logging for "net.kentcom" = ALL, your Confluence administrator
will know how to do all this. You can filter only the net.kentcom lines
from the log file before sending, for your privacy.

Thanks
