### ISSUE TITLE
java.lang.String cannot be cast to java.lang.Boolean - EasyForums last Version

### ISSUE THREAD

**Issue by AlexL777** [chris-kent/Easy-Forums#11]
Hello Developers,

I have made today EasyForums update, the last version installed and see in the forum frontend this error.

`Error rendering the macro 'forum': java.lang.String can not be cast to java.lang.Boolean`

Can you please look at this again.

Thanks in advance.

P.S. Confluence Server 6.0.6 is used.

**Comment by chris-kent** [comment]
Hi this had been fixed on the latest version. Please install and let me
know if ok

**Comment by AlexL777** [comment]
I have just installed the last EasyForums version from the Confluence Marketplace. Also, I manually deleted the Confluence plugin cache. The error is still displayed at http://confluence.liebrecht-projekte.de:8060/display/FOR.

I can not tell you what it can be or what it might have to do with my installation.

But the very latest plugin version is installed with me.

**Comment by chris-kent** [comment]
I'll try to debug this, I thought I fixed it already :(

As for your site, I can't see it, gives me this error:
The confluence.liebrecht-projekte.de page isn’t working

*confluence.liebrecht-projekte.de
<http://confluence.liebrecht-projekte.de>* didn’t
send any data.
ERR_EMPTY_RESPONSE

**Comment by AlexL777** [comment]
Sorry, Confluence of mine was something offline and I have installed the plugin again. Now this works so far and the forum is displayed.

I think if I have something else, I'll sign up here on GitHub. Thanks by the way for the new version of EasyForums :smile:

**Comment by AlexL777** [comment]
My Confluence is under http://confluence.liebrecht-projekte.de:8060

**Comment by chris-kent** [comment]
OK, I see it, I also found the bug with the new setting to show the
sidebar.  This is now hopefully fixed in version 2.13, which I just
published.
By the way, I removed versions 2.10, 2.11 and 2.12 from the market place.

Thanks for all your help making this plugin better.

Cheers
Chris

**Comment by AlexL777** [comment]
Cool, that pleases me and the new plugin version I just installed. The with the sidebar I will still try. I like to have it done and together we have improved your plugin. Thanks for that!
