### ISSUE TITLE
Macros do not display

### ISSUE THREAD

**Issue by yaacovw** [chris-kent/Easy-Forums#12]
Hi,
I am trying to evaluate Easy Forums for our company's community site. Downloaded the latest version and added it to our Confluence. Created the new Space, a new Forum, and added a topic. Everything seemed to work fine (tried from two different users and anonymous access) as long as the Community, Forum, and topic were displayed in "full screen" mode. But, when I clicked on the Community Home Page link in the breadcrumbs or the Forum link, the Space was displayed with the sidebar and the macros give the following error:  "Error rendering macro 'forum' : null" (see attachment)
![easyforumerror](https://cloud.githubusercontent.com/assets/13232642/24439240/b6634c88-1455-11e7-8f38-8c67dfbc2bb1.png)

**Comment by chris-kent** [comment]
Hi There,

This screenshot looks different to the Easy Forums plugin,  In my plugin, I do not show the breadcrumbs, and by default the sidebar is turned off.
By any chance do you have Community Forums installed too?  I have a feeling that you do and it is likely that Easy Forums and Community Forums conflict (possibly using the same macro name).

Can I suggest the following.

1. Disable all other Forum plugins, especially Community.
2. Retry Easy Forums using the Create Space template to get you started in a new space. Do not create your space manually, use the Easy Forums space template.
3. If you still see errors evaluating Easy Forums, then turn on logging using "net.kentcom" class name and send me all the matching lines from your log file.

Hope this helps, if you have any more issues, please respond and I'll help you out.

Cheers
Chris

**Comment by yaacovw** [comment]
Chris, hi

Thank you for your speedy reply.
Regarding your suggestions:

  1.  I do not have any Forum Add-On installed except for EasyForum, but I double-checked just to make sure and did not find any conflicting evidence.
  2.  I deleted the existing Forum Space (that was created with your space template) and then created a new one.
  3.  I do not currently have access to the log file, although I did add the setting to log the Easy Forum actions. Will try to access it when I am in the office.
In addition, after creating the new Forum Space I managed to recreate the problem – the sequence of actions (with attached screenshots) was:

  1.  Created the new Forum Space – and changed the permissions to allow both a second user to access the forum and also allow limited access by anonymous users.
  2.  Create new Forum using the template (see screenshot) – worked as expected.
  3.  Created a new topic from the template (see screenshot) – worked as expected
  4.  Logged in with second account (from a different browser) and added a reply comment (see screenshot) – both users displayed as expected
  5.  Went back-and-forth between pages from both user accounts and display continued to work.
  6.  Accessed the Space from an anonymous account (using the URL of the Space) – displayed correctly
  7.  Went into the topic – continued to display correctly
  8.  Added an anonymous comment to the topic
  9.  Used the Browser's back button to go back to the Forum page in anonymous access and received the display in the last screenshot.
  10. Now all three users displayed the Space with the sidebar and problems displaying the macros.
Just as a note – you can see that the breadcrumbs are included in all of the screenshots.
As an additional question – does Easy Forum use the page labels at all?

Hope this helps,
yaacov

**Comment by chris-kent** [comment]
Hi there.

That is s great discription of the problem. Now that you mention the
anonymous user i think i know what is causing this. My plugin has a few
areas where it looks up user details, this will fail for anonymous users
😂. I have hit this before, must be one lying around. ..

I should be able to get you a fix in the next 24 hours.

As for page labels, yes my plugin users them but users can also add own
labels. If you want to show them in topics, then this is configurable in
the admin pages.

Cheers
Chris



On 29 Mar 2017 11:15 PM, "Yaacov Weingarten" <notifications@github.com>
wrote:

Chris, hi

Thank you for your speedy reply.
Regarding your suggestions:

1. I do not have any Forum Add-On installed except for EasyForum, but I
double-checked just to make sure and did not find any conflicting evidence.
2. I deleted the existing Forum Space (that was created with your space
template) and then created a new one.
3. I do not currently have access to the log file, although I did add the
setting to log the Easy Forum actions. Will try to access it when I am in
the office.
In addition, after creating the new Forum Space I managed to recreate the
problem – the sequence of actions (with attached screenshots) was:

1. Created the new Forum Space – and changed the permissions to allow both
a second user to access the forum and also allow limited access by
anonymous users.
2. Create new Forum using the template (see screenshot) – worked as
expected.
3. Created a new topic from the template (see screenshot) – worked as
expected
4. Logged in with second account (from a different browser) and added a
reply comment (see screenshot) – both users displayed as expected
5. Went back-and-forth between pages from both user accounts and display
continued to work.
6. Accessed the Space from an anonymous account (using the URL of the
Space) – displayed correctly
7. Went into the topic – continued to display correctly
8. Added an anonymous comment to the topic
9. Used the Browser's back button to go back to the Forum page in anonymous
access and received the display in the last screenshot.
10. Now all three users displayed the Space with the sidebar and problems
displaying the macros.
Just as a note – you can see that the breadcrumbs are included in all of
the screenshots.
As an additional question – does Easy Forum use the page labels at all?

Hope this helps,
yaacov

**Comment by yaacovw** [comment]
Hi,

Attached is the promised log file filtered to only the Add-Ons messages

Regarding the labels – is there a way to label all topics in a particular forum with labels that identify the forum?

Thanx,
yaacov

**Comment by chris-kent** [comment]
Hi,
I have fixed this issue, the plugin did not actually support Anonymous users to make comments :(. All sorted now, please install version 2.14..

I also implemented your new request, Forum labels are automatically copied to new Topics.

If there is anything else I can do to improve the plugin, please raise another issue.

Cheers
Chris
