### ISSUE TITLE
New occurrences of the macro 'forum' : null error

### ISSUE THREAD

**Issue by yaacovw** [chris-kent/Easy-Forums#13]
Hi again,

Thank you for the fix of the previous issue. But I seem to be causing this issue to occur in different instances. Downloaded the latest (2.14) version - deleted my old Forum Space, created a new space, added two forums - everything seemed to display OK.
I then went to the documentation to see how I define the moderators for the Space (as an aside - the moderators are for the Space? Can they be localized to be moderators for specific forums?). Went to the User Management and defined two moderators. Now the forums (created previously) display OK, but the Space page is displayed as shown in the attachment.
Will try to see if I can get the log to you later.

Thanx,
yaacov
![spacepage_4apr](https://cloud.githubusercontent.com/assets/13232642/24643168/c228ccb4-1914-11e7-8f09-8e34d009e516.png)

**Comment by chris-kent** [comment]
Hi there,

I'm so sorry this is happening, please send through the logs, but also
please include any crash logging/debugging from the log file so I can see
the error and the code that causes the error.

Thanks
Chris

**Comment by yaacovw** [comment]
Hi,

Could not get the log of the occurrence earlier this morning – so I did the following and got similar results:

  1.  Created a new EasyForum Space
  2.  Created a new Forum
  3.  Went back to Space welcome page using the breadcrumbs
  4.  Create a second new Forum
  5.  Went back to the Space welcome page using the breadcrumbs
Welcome page is broken with the macro 'forum':null error

Attached are the full log for the period of the actions and the file with the "kentcom" lines.

Hope this helps,
yaacov

**Comment by chris-kent** [comment]
Hi,
If you tried to attach the log file, then I can't see it. Can you try again please, you will need to attach files in github.
Cheers
Chris

**Comment by chris-kent** [comment]
Also, I will need the lines in the file with the exception tract, so I can diagnose the problem. ie. I need more than just the lines with net.kentcom... 

Thanks

**Comment by yaacovw** [comment]
[kentcomLog.txt](https://github.com/chris-kent/Easy-Forums/files/892809/kentcomLog.txt)


[atlassian-confluence (1).zip](https://github.com/chris-kent/Easy-Forums/files/892813/atlassian-confluence.1.zip)

**Comment by chris-kent** [comment]
Aha, I found it, it is because there are no topics in any of the forums, hence the sort by date is crashing.
I have fixed this in ver 2.15, but to get past this until I publish, simply create topics in all forums, or change the sort column to something other than date.

Cheers
Chris

**Comment by chris-kent** [comment]
Just published 2.15...
