### ISSUE TITLE
Anonymous create topic - causes the null pointer error.

### ISSUE THREAD

**Issue by yaacovw** [chris-kent/Easy-Forums#14]
Hi Chris,
Found another instance where you macros return null and don't display properly. 
Here's the scenario -
1. Created space with several topics
2. Changed permissions to allow anonymous users to create a new topic only (i.e. no attachments and no comments).
3. Open the Forum space from anonymous user and go to one of the topics
4. Click on "Create New Topic" - everything seems to be working up to this point.
5. Fill in the new topic page and Save. Topic displays properly
6. Go back to the forum page - and the list of topics macro returns Null and display is bad
7. Other forums and home-page display properly from all users, the forum with the anonymous topic does not display.

This is the timestamp of the null pointer error: 2017-04-05 12:28:28,
Sorry that I am finding all of these 'bugs',
yaacov
[AnonymousTopicLog.txt](https://github.com/chris-kent/Easy-Forums/files/895865/AnonymousTopicLog.txt)

**Comment by chris-kent** [comment]
Hi Yaacov,

Yet another one down... Please download version 2.16, this has been fixed.
Keep up the testing - hopefully you won't find anymore :)

Cheers
Chris
