### ISSUE TITLE
Is this open to public or only for internal JIRA team members

### ISSUE THREAD

**Issue by ChrisJ2Inn** [chris-kent/Easy-Forums#16]
Hey Chris,

Our company uses Atlassian for all of our internal needs, as well as public documentaiton for our customers. 

We are looking at finding a way for our customers to post tech support questions in a forum-like manner. 

Would you product (Easy Forums) be able to do this or is it for internal team members only?  How would our customers use the forums..do they just sign up and post a question?

**Comment by chris-kent** [comment]
Hi,

Firstly, this plugin is for Confluence and not JIRA (I assume this was a typo :) 

If your Confluence instance is public, then yes you can use Easy Forums for both internal and anonymous users, if you setup the Space permissions to allow anonymous users access - easy.

As for using, it is simply bolts into Confluence Page and Comment behavior, Pages contain the Topic (the original Post) and Comments are used for users to Answer or add additional posts to the Topic. Have a look at the User Guide, [(https://github.com/chris-kent/easy-forums/wiki/Easy-Forums)]. 

Depending on whether you wanted the users to be anonymous or not would depend on whether you force them to create accounts or not, this is entirely up to you, and also your Confluence license limit.

Good luck, and I'm sure this plugin will provide everything you need from a forum,and if not, I am always happy to add customer requests if it is technically possible.

Cheers
Chris
