### ISSUE TITLE
Unable to enable add on in Confluence

### ISSUE THREAD

**Issue by lpassi** [chris-kent/Easy-Forums#21]
Hi - we are running Confluence version 5.9.4. We recently attempted to install the Easy Forums add on version 3.4 but we aren't able to Enable the plug in. It should be compatible shouldn't it? Is there a different version we should try?

**Comment by chris-kent** [comment]
Hi,
Yes that should be compatible. If the plugin is not being enabled, then there will be an error in the Confluence log file. Can you please send me the error from the log file.

It would help if you enabled logging by adding net.kentcom = ALL in the Logging and Profiling section in the Confluence Administration, and then tried to enable the plugin.

Thanks
Chris

**Comment by lpassi** [comment]
Hi, thanks for the quick reply.

I have extracted the log file I deleted a load of it though, as it would be too big to send you, but I think it captures the problems with your add on.

Kind Regards,

Luke Passi
I.T. Operations Manager
DDI:        +44 (0)1923 320005
Email:     lpassi@salmon.com<mailto:lpassi@salmon.com>
Skype:   lpassi@salmon.com<mailto:lpassi@salmon.com>  

[cid:image001.png@01D30ABF.CC2B56E0]<https://salmon.com/en/ecommerce-platform-research-report/>

[cid:image002.jpg@01D30ABF.CC2B56E0]<https://twitter.com/salmonltd> [cid:image003.jpg@01D30ABF.CC2B56E0] <https://www.linkedin.com/company/salmon>  [cid:image004.jpg@01D30ABF.CC2B56E0] <https://plus.google.com/+SalmonLtd/posts>  [cid:image005.jpg@01D30ABF.CC2B56E0] <https://www.facebook.com/SalmonLtd>  [cid:image006.jpg@01D30ABF.CC2B56E0] <http://www.pinterest.com/salmonltd/>  [cid:image007.jpg@01D30ABF.CC2B56E0] <https://www.youtube.com/user/salmonlimited>  [cid:image008.jpg@01D30ABF.CC2B56E0] <http://www.slideshare.net/salmonltd>

**Comment by chris-kent** [comment]
Hi,

I see 2 problems, one I have not seen before, but you may be able to simply
fix this. The plugin cannot create the Group name   "easyforums-moderators".
I have not seen this before, maybe as a workaround, if you manually create
this group, then the plugin might work, please give that a try and
re-enable the plugin.  Let me know if this fixes the problem?

I also see this in the log:
2017-07-27 09:31:05,758 WARN [ajp-nio-8009-exec-18]
[plugins.cute.license.CuteLicenseService] isValidLicenseInstalled License
found but invalid.
-- referer:
https://my.atlassian.com/addon/success?type=try&addOnKey=net.kentcom.easy-forums&addOnName=Easy+Forums&addOnSen=L10078544&licenseId=10078544&parentName=Confluence+%28Server%29&referrer=&callback=https%3A%2F%2Fwiki-stage.salmon.com%2Fplugins%2Fservlet%2Fupm%2Flicense%2Fnet.kentcom.easy-forums&licensefieldname=license
| url: /plugins/servlet/upm | userName: lpassi
2017-07-27 09:31:05,758 WARN [ajp-nio-8009-exec-18]
[plugins.cute.license.CuteLicenseService] isValidLicenseInstalled License
found but invalid.
--

So I'm not sure why the license is invalid, maybe grab another trial if you
can!!!

Cheers
Chris

**Comment by lpassi** [comment]
OK thanks, will try this and report back.

Kind Regards,

Luke Passi
I.T. Operations Manager
DDI:        +44 (0)1923 320005
Email:     lpassi@salmon.com<mailto:lpassi@salmon.com>
Skype:   lpassi@salmon.com<mailto:lpassi@salmon.com>  

[cid:image001.png@01D30AC2.FF092940]<https://salmon.com/en/ecommerce-platform-research-report/>

[cid:image002.jpg@01D30AC2.FF092940]<https://twitter.com/salmonltd> [cid:image003.jpg@01D30AC2.FF092940] <https://www.linkedin.com/company/salmon>  [cid:image004.jpg@01D30AC2.FF092940] <https://plus.google.com/+SalmonLtd/posts>  [cid:image005.jpg@01D30AC2.FF092940] <https://www.facebook.com/SalmonLtd>  [cid:image006.jpg@01D30AC2.FF092940] <http://www.pinterest.com/salmonltd/>  [cid:image007.jpg@01D30AC2.FF092940] <https://www.youtube.com/user/salmonlimited>  [cid:image008.jpg@01D30AC2.FF092940] <http://www.slideshare.net/salmonltd>

**Comment by lpassi** [comment]
Cool – that seems to have solved it. New license and manually created the group in AD.

Thanks a lot for the help!

Kind Regards,

Luke Passi
I.T. Operations Manager
DDI:        +44 (0)1923 320005
Email:     lpassi@salmon.com<mailto:lpassi@salmon.com>
Skype:   lpassi@salmon.com<mailto:lpassi@salmon.com>  

[cid:image001.png@01D30AC3.CE678E70]<https://salmon.com/en/ecommerce-platform-research-report/>

[cid:image002.jpg@01D30AC3.CE678E70]<https://twitter.com/salmonltd> [cid:image003.jpg@01D30AC3.CE678E70] <https://www.linkedin.com/company/salmon>  [cid:image004.jpg@01D30AC3.CE678E70] <https://plus.google.com/+SalmonLtd/posts>  [cid:image005.jpg@01D30AC3.CE678E70] <https://www.facebook.com/SalmonLtd>  [cid:image006.jpg@01D30AC3.CE678E70] <http://www.pinterest.com/salmonltd/>  [cid:image007.jpg@01D30AC3.CE678E70] <https://www.youtube.com/user/salmonlimited>  [cid:image008.jpg@01D30AC3.CE678E70] <http://www.slideshare.net/salmonltd>

**Comment by chris-kent** [comment]
That is good to know, but now I am keen to understand why that failed?  Do
you have any idea why the plugin could not create user group? You may not
know, but it could be something with permissions?

If you don't know, then don't worry, I'll ask Atlassian.

Cheers
Chris

**Comment by lpassi** [comment]
I suspect our version of Confluence doesn’t’ allow right back to our Active Directory via the LDAP connection.

Kind Regards,

Luke Passi
I.T. Operations Manager
DDI:        +44 (0)1923 320005
Email:     lpassi@salmon.com<mailto:lpassi@salmon.com>
Skype:   lpassi@salmon.com<mailto:lpassi@salmon.com>  

[cid:image001.png@01D30AC5.CFBF1D40]<https://salmon.com/en/ecommerce-platform-research-report/>

[cid:image002.jpg@01D30AC5.CFBF1D40]<https://twitter.com/salmonltd> [cid:image003.jpg@01D30AC5.CFBF1D40] <https://www.linkedin.com/company/salmon>  [cid:image004.jpg@01D30AC5.CFBF1D40] <https://plus.google.com/+SalmonLtd/posts>  [cid:image005.jpg@01D30AC5.CFBF1D40] <https://www.facebook.com/SalmonLtd>  [cid:image006.jpg@01D30AC5.CFBF1D40] <http://www.pinterest.com/salmonltd/>  [cid:image007.jpg@01D30AC5.CFBF1D40] <https://www.youtube.com/user/salmonlimited>  [cid:image008.jpg@01D30AC5.CFBF1D40] <http://www.slideshare.net/salmonltd>

**Comment by chris-kent** [comment]
Fixed in ver 3.5
