### ISSUE TITLE
Increase maximum moderators per forum

### ISSUE THREAD

**Issue by cfrazier789** [chris-kent/Easy-Forums#22]
Hi, 

Can I make a feature request to increase the maximum number of moderators permitted for each forum? We are currently evaluating Easy Forums for use and would like more than 3 moderators, which may be different for each forum. Has this been prioritized for a next round of updates?

Thanks,
Chris

**Comment by chris-kent** [comment]
Hi Chris,

I can make the max number of moderators configurable in the configuration admin page. This I will do in the next release. Please watch out for this.

Cheers
Chris

**Comment by chris-kent** [comment]
Implemented in Version 3.7
