### ISSUE TITLE
Macro Forum can not be rendered for Anonymous Users

### ISSUE THREAD

**Issue by AlexL777** [chris-kent/Easy-Forums#24]
Hello Developers,

I have again discovered a bug when the page is opened with the EasyForums. The Macro "Forum" can not be rendered. Value is at `null`.

Can you possibly upload an addon update in Marketplace?

Thanks in advance.

P.S. I use Confluence 6.4.0 and EasyForums version, which I had in the Marketplace.

**Comment by chris-kent** [comment]
This has been fixed in version 3.9
