### ISSUE TITLE
German Language not correct showing

### ISSUE THREAD

**Issue by AlexL777** [chris-kent/Easy-Forums#28]
Hi Developer,

Recently you have been able to use German at EasyForums, but unfortunately this is not quite correct in the frontend.

Please take a look at http://apps-tools-cms.de:8040/display/CMSLIN/EasyForums. There right at the beginning of the forum in the tables, the German umlauts are not displayed correctly.

Can this be fixed?

Thank you in advance.

**Comment by chris-kent** [comment]
Hi Alex,
Yes this can be fixed, I am working with another German customer to get this working correctly, it has to do with the file encoding of the German translation file. O hope to have this rectified soon.

Thanks

**Comment by chris-kent** [comment]
Hi,
This has been fixed in ver 3.14.
Please let me know if there are any German translation issues.
Cheers
