### ISSUE TITLE
easyforums-moderators group question

### ISSUE THREAD

**Issue by roussbo** [chris-kent/Easy-Forums#31]
Hello,

I have a question regarding the easyforums-moderators group. Is it possible to replace it with another one? My problem is that we use Confluence groups with a active directory connection and we can not add users to a local Confluence group such as easyforums-moderators that is not an active directory one. 

Thank you!

Best 
Borislav

**Comment by chris-kent** [comment]
Hi  Borislav,

At the moment it is not possible to change the moderators group. I will
need to add this to the road map.

Cheers
