### ISSUE TITLE
Problem with forum search

### ISSUE THREAD

**Issue by JTFrings** [chris-kent/Easy-Forums#34]
**Describe the bug**
We installed Easy Forums on our test environment and created a forums space and some forums. The search feature adds a search term to the orginal term, leading to unseuccesful searches. 

**To Reproduce**
1. In the forums space, enter a search term,e.g. "X"in the Search field.
2. The resulting search tries to find "ancestorIds:31391800 AND X"
**Expected behavior**
Show results for "X" only.

**Versions (please complete the following information):**
 - Confluence: 6.15.2
 - Plugin: 3.16
 - Data Center: Not Supported

**Comment by chris-kent** [comment]
Hi,

The search used in the Forums is the PageTree Search macro. Hence the
reason that the ancestor id is added to the search. This is the behaviour
of page tree search macro (you can test this for yourself on any parent
page), which was chosen for this search to restrict searches for topics
within the forum only.

If you wish to search ALL forums, then the search should be carried out
from the Home page of the space, which also uses the PageTree search to
prevent the search from finding results from other spaces.

If this is the behaviour you are seeing, then it is by design.

I hope this helps

Cheers
Chris

**Comment by JTFrings** [comment]
Hi Chris,

my problem is that I don't find anything until I delete the ancestor id form the search terms. Then the search works fine.

Any suggestions how to make it work?

Cheers,
Thies

**Comment by JTFrings** [comment]
Hi again,

I found that the problem lies with the "AND". If I replace it with "and" it works. Is there a language setting problem or something in that line?

Thies

**Comment by chris-kent** [comment]
Hi there

Ill have a look at this tomorrow. But the template uses the page tree
macro. My plugin doesn't add the anscestor or the and.

This could be an issue with the page tree macro.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi Thies,

I have done some extensive testing, on my versions of Confluence and I
can't fault the behaviour. It works happily for me.

If this is still a problem for you, can I suggest the following.

On any Forum page (or the Easy Forums Home page) that does not give you the
correct search results, edit the page and add in the PageTreeSearch macro.
If you don't know what the PageTreeSearch function does, please research it
on the Confluence help pages. It is well documented.
Use this instance of the search on the page and see if the results is any
better. If not, then this is an Atlassian issue :(. Most likely something
wrong in your environment.

I do know that the lucene search engine in Confluence is pretty crap. I
don't like it and often I have to retype my search phrase differently until
I get the result.

If the problem only persists using the search tool built into the plugin,
can you please provide me with the exact search phrase you are using so I
can try this for myself. And if it is not obvious, what content you have on
a child page that it doesn't show results for.

hth

Chris
