### ISSUE TITLE
Attachments possible?

### ISSUE THREAD

**Issue by thomasbuettner69** [chris-kent/Easy-Forums#5]
Hi,
I do not know, if I am right here with my question... we areconsidering to add Easy Forums to our confluence platform and have one - quite crucial - question: Is it possible to add attachments to the topics or posts? If yes, are there any size or format restrictions?
Thanks in advance for your answer.
Best regards,
Thomas

**Comment by chris-kent** [comment]
Hi Thomas,

Yes it is possible to add attachments to Topics and Posts. Most of the
standard Confluence editing is available in the Forums pages, the only
caviet is that the user needs to have edit permissions, which is controlled
either by the Space permissions or the Easy Forums configuration page, just
the same as any Confluence page.

Please enjoy and let me know if you have any issues, I am happy to help.

Chris

**Comment by thomasbuettner69** [comment]
Hi, Chris,
thanks a lot - I think I will use your forum plugin for communication and sharing of knowlegdge within my team.
Best regards,
Thomas

**Comment by chris-kent** [comment]
Hi Thomas,

Glad to hear, and I'm happy to make improvements, so if there is something
that you feel would make this plugin better, please let me know...

Cheers
Chris
