### ISSUE TITLE
I would like to see the number of topic views in the forum

### ISSUE THREAD

**Issue by AlexL777** [chris-kent/Easy-Forums#6]
Hello Developers,

Now I have also discovered this Confluence Server Plugin. I would like a new feature in the forum. Would it be technically and real feasible to have the number of topic views displayed in the line with the forum topic.

This would leave the forum reader first impression and it also looks better for outsiders, if a topic has been called often.

That would be my feedback to the forum after a few hours of work with it.

Thank you and I look forward to your feedback here in the issue.

**Comment by chris-kent** [comment]
Hi There,

Thank you for your feedback, just to clarify, are you asking that on the
Forum pages (which lists the Topics within the Forum), that a new Column
should be added to the table, called "Views", which shows how many
visits/views each Topic page has had?

If so, then yes I believe I could implement this.

Thanks
Chris

**Comment by AlexL777** [comment]
Hello,

Exactly, that's what I mean. It would be great if another box with the Topic-Views could be added.

If this is feasible, I would be very happy as a new EasyForums user.

Thanks in advance.

**Comment by chris-kent** [comment]
Hi There,

I have just uploaded a new version of the plugin with this feature added -
enjoy.

Please let me know of any other improvements :)

Cheers

**Comment by AlexL777** [comment]
Hello Chris,

 

Thanks for adding this new feature. It looks great in the frontend and if I have some suggestions for improvement, I'll let you know about GitHub.

 

Greetings, Alexander

 

 

Alexander Liebrecht
Alte Warnemünder Chaussee 25
D-18109 Rostock
eMail: power_sash@gmx.net
Tel: +49 038133795190
------------------------------
Kleinunternehmer nach §19 der Kleinunternehmerregelung. Steuernummer 079/245/06541. Finanzamt Rostock. Meine Rechnungen weisen keinerlei Mehrwertsteuer aus.
------------------------------
CMS-Installation-Service >> https://internetblogger.blog
Blog >> https://internetblogger.de
Confluence >> http://confluence.liebrecht-projekte.de:8060

 
 

Gesendet: Dienstag, 21. Februar 2017 um 12:11 Uhr
Von: chris-kent <notifications@github.com>
An: chris-kent/Easy-Forums <Easy-Forums@noreply.github.com>
Cc: "Alexander Liebrecht" <power_sash@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [chris-kent/Easy-Forums] I would like to see the number of topic views in the forum (#6)

Hi There,

I have just uploaded a new version of the plugin with this feature added -
enjoy.

Please let me know of any other improvements :)

Cheers
