### ISSUE TITLE
Sorted Topics in a Forum

### ISSUE THREAD

**Issue by nofi79** [chris-kent/Easy-Forums#7]
How to configure a Forum list of topics to start sorted by Status ? I understand that we can get it sorted after load the page. I would like that everyone have it sorted by status at first and able to change after the page load.

**Comment by chris-kent** [comment]
Hi,
This has been implemented, please download ver 2.9 and give it a try.
To configure the initial sort column, go to the Easy Forums admin page.
Cheers

**Comment by nofi79** [comment]
Thank you for your help. I will ask the IT team to set it for us.

**Comment by chris-kent** [comment]
Hi there,

Have you installed the latest version?

This feature was just included. Please download and use the easy forums
admin page to configure this feature

Cheers
