### ISSUE TITLE
Can I view last forum topics in the sidebar of Confluence Server - with a macro

### ISSUE THREAD

**Issue by AlexL777** [chris-kent/Easy-Forums#9]
Hello Developers,

I have an interesting request to EasyForums. Can I view last forum topics in Confluence 6.0.6 Sidebar? It would be interesting to know whether a macro already exists or if you can develop that. I know it's a lot of work, but maybe you would.

Then I wait for your feedback.

Thanks in advance.

**Comment by chris-kent** [comment]
Hi there,

By design I hide the sidebar to keep the interface clean, So for you, I have now made this configurable as to whether to show the sidebar or not. In my latest version 2.10, go to admin page for Easy Forums and enable the sidebar.

I hope this gives you what you want.

Cheers
Chris
